version: "3.8"

networks:
  payment-processor:
    external: true
  rinha-network:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  api1:
    build: .
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://user:password@db:5432/rinha?sslmode=disable
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - db
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  api2:
    build: .
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://user:password@db:5432/rinha?sslmode=disable
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - db
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rinha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  redis:
    image: redis:7-alpine
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"

volumes:
  postgres_data:
