networks:
  payment-processor:
    external: true
  rinha-network:
    driver: bridge

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rinha-network
    ports:
      - "5432:5432"  # Para debug
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rinha"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  redis:
    image: redis:7-alpine
    networks:
      - rinha-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"

  api1:
    build: .
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/rinha?sslmode=disable
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rinha-network
      - payment-processor
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "netstat -ln | grep :3000 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  api2:
    build: .
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/rinha?sslmode=disable
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rinha-network
      - payment-processor
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "netstat -ln | grep :3000 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    networks:
      - rinha-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9999/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

volumes:
  postgres_data: